// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/baeldung.proto

package cn.tuyucheng.taketoday.protobuf;

public final class BaeldungTraining {
    private static final com.google.protobuf.Descriptors.Descriptor internal_static_baeldung_Course_descriptor;
    private static final com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_baeldung_Course_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor internal_static_baeldung_Student_descriptor;
    private static final com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_baeldung_Student_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor internal_static_baeldung_Student_PhoneNumber_descriptor;
    private static final com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_baeldung_Student_PhoneNumber_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

    static {
        String[] descriptorData = {"\n\030resources/baeldung.proto\022\010baeldung\"M\n\006" + "Course\022\n\n\002id\030\001 \001(\005\022\023\n\013course_name\030\002 \001(\t\022"
                + "\"\n\007student\030\003 \003(\0132\021.baeldung.Student\"\352\001\n\007" + "Student\022\n\n\002id\030\001 \001(\005\022\022\n\nfirst_name\030\002 \001(\t\022"
                + "\021\n\tlast_name\030\003 \001(\t\022\r\n\005email\030\004 \001(\t\022,\n\005pho" + "ne\030\005 \003(\0132\035.baeldung.Student.PhoneNumber\032" + "H\n\013PhoneNumber\022\016\n\006number\030\001 \001(\t\022)\n\004type\030\002"
                + " \001(\0162\033.baeldung.Student.PhoneType\"%\n\tPho" + "neType\022\n\n\006MOBILE\020\000\022\014\n\010LANDLINE\020\001B)\n\025com." + "baeldung.protobufB\020BaeldungTrainingb\006pro", "to3"};
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
            public com.google.protobuf.ExtensionRegistry assignDescriptors(com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                return null;
            }
        };
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData, new com.google.protobuf.Descriptors.FileDescriptor[]{}, assigner);
        internal_static_baeldung_Course_descriptor = getDescriptor().getMessageTypes().get(0);
        internal_static_baeldung_Course_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(internal_static_baeldung_Course_descriptor, new String[]{"Id", "CourseName", "Student",});
        internal_static_baeldung_Student_descriptor = getDescriptor().getMessageTypes().get(1);
        internal_static_baeldung_Student_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(internal_static_baeldung_Student_descriptor, new String[]{"Id", "FirstName", "LastName", "Email", "Phone",});
        internal_static_baeldung_Student_PhoneNumber_descriptor = internal_static_baeldung_Student_descriptor.getNestedTypes().get(0);
        internal_static_baeldung_Student_PhoneNumber_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(internal_static_baeldung_Student_PhoneNumber_descriptor, new String[]{"Number", "Type",});
    }

    private BaeldungTraining() {
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    }

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }

    public interface CourseOrBuilder extends
            // @@protoc_insertion_point(interface_extends:baeldung.Course)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional int32 id = 1;</code>
         */
        int getId();

        /**
         * <code>optional string course_name = 2;</code>
         */
        String getCourseName();

        /**
         * <code>optional string course_name = 2;</code>
         */
        com.google.protobuf.ByteString getCourseNameBytes();

        /**
         * <code>repeated .baeldung.Student student = 3;</code>
         */
        java.util.List<Student> getStudentList();

        /**
         * <code>repeated .baeldung.Student student = 3;</code>
         */
        Student getStudent(int index);

        /**
         * <code>repeated .baeldung.Student student = 3;</code>
         */
        int getStudentCount();

        /**
         * <code>repeated .baeldung.Student student = 3;</code>
         */
        java.util.List<? extends StudentOrBuilder> getStudentOrBuilderList();

        /**
         * <code>repeated .baeldung.Student student = 3;</code>
         */
        StudentOrBuilder getStudentOrBuilder(int index);
    }

    public interface StudentOrBuilder extends
            // @@protoc_insertion_point(interface_extends:baeldung.Student)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional int32 id = 1;</code>
         */
        int getId();

        /**
         * <code>optional string first_name = 2;</code>
         */
        String getFirstName();

        /**
         * <code>optional string first_name = 2;</code>
         */
        com.google.protobuf.ByteString getFirstNameBytes();

        /**
         * <code>optional string last_name = 3;</code>
         */
        String getLastName();

        /**
         * <code>optional string last_name = 3;</code>
         */
        com.google.protobuf.ByteString getLastNameBytes();

        /**
         * <code>optional string email = 4;</code>
         */
        String getEmail();

        /**
         * <code>optional string email = 4;</code>
         */
        com.google.protobuf.ByteString getEmailBytes();

        /**
         * <code>repeated .baeldung.Student.PhoneNumber phone = 5;</code>
         */
        java.util.List<Student.PhoneNumber> getPhoneList();

        /**
         * <code>repeated .baeldung.Student.PhoneNumber phone = 5;</code>
         */
        Student.PhoneNumber getPhone(int index);

        /**
         * <code>repeated .baeldung.Student.PhoneNumber phone = 5;</code>
         */
        int getPhoneCount();

        /**
         * <code>repeated .baeldung.Student.PhoneNumber phone = 5;</code>
         */
        java.util.List<? extends Student.PhoneNumberOrBuilder> getPhoneOrBuilderList();

        /**
         * <code>repeated .baeldung.Student.PhoneNumber phone = 5;</code>
         */
        Student.PhoneNumberOrBuilder getPhoneOrBuilder(int index);
    }

    /**
     * Protobuf type {@code baeldung.Course}
     */
    public static final class Course extends com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:baeldung.Course)
            CourseOrBuilder {
        public static final int ID_FIELD_NUMBER = 1;
        public static final int COURSE_NAME_FIELD_NUMBER = 2;
        public static final int STUDENT_FIELD_NUMBER = 3;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:baeldung.Course)
        private static final Course DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<Course> PARSER = new com.google.protobuf.AbstractParser<Course>() {
            public Course parsePartialFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
                return new Course(input, extensionRegistry);
            }
        };

        static {
            DEFAULT_INSTANCE = new Course();
        }

        private int bitField0_;
        private int id_;
        private volatile Object courseName_;
        private java.util.List<Student> student_;
        private byte memoizedIsInitialized = -1;

        // Use Course.newBuilder() to construct.
        private Course(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
        }

        private Course() {
            id_ = 0;
            courseName_ = "";
            student_ = java.util.Collections.emptyList();
        }

        private Course(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {

                            id_ = input.readInt32();
                            break;
                        }
                        case 18: {
                            String s = input.readStringRequireUtf8();

                            courseName_ = s;
                            break;
                        }
                        case 26: {
                            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                                student_ = new java.util.ArrayList<Student>();
                                mutable_bitField0_ |= 0x00000004;
                            }
                            student_.add(input.readMessage(Student.parser(), extensionRegistry));
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                    student_ = java.util.Collections.unmodifiableList(student_);
                }
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return BaeldungTraining.internal_static_baeldung_Course_descriptor;
        }

        public static Course parseFrom(com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Course parseFrom(com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Course parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Course parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Course parseFrom(java.io.InputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
        }

        public static Course parseFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Course parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input);
        }

        public static Course parseDelimitedFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static Course parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
        }

        public static Course parseFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(Course prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static Course getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<Course> parser() {
            return PARSER;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        protected FieldAccessorTable internalGetFieldAccessorTable() {
            return BaeldungTraining.internal_static_baeldung_Course_fieldAccessorTable.ensureFieldAccessorsInitialized(Course.class, Builder.class);
        }

        /**
         * <code>optional int32 id = 1;</code>
         */
        public int getId() {
            return id_;
        }

        /**
         * <code>optional string course_name = 2;</code>
         */
        public String getCourseName() {
            Object ref = courseName_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                courseName_ = s;
                return s;
            }
        }

        /**
         * <code>optional string course_name = 2;</code>
         */
        public com.google.protobuf.ByteString getCourseNameBytes() {
            Object ref = courseName_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                courseName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>repeated .baeldung.Student student = 3;</code>
         */
        public java.util.List<Student> getStudentList() {
            return student_;
        }

        /**
         * <code>repeated .baeldung.Student student = 3;</code>
         */
        public java.util.List<? extends StudentOrBuilder> getStudentOrBuilderList() {
            return student_;
        }

        /**
         * <code>repeated .baeldung.Student student = 3;</code>
         */
        public int getStudentCount() {
            return student_.size();
        }

        /**
         * <code>repeated .baeldung.Student student = 3;</code>
         */
        public Student getStudent(int index) {
            return student_.get(index);
        }

        /**
         * <code>repeated .baeldung.Student student = 3;</code>
         */
        public StudentOrBuilder getStudentOrBuilder(int index) {
            return student_.get(index);
        }

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1)
                return true;
            if (isInitialized == 0)
                return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
            if (id_ != 0) {
                output.writeInt32(1, id_);
            }
            if (!getCourseNameBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessage.writeString(output, 2, courseName_);
            }
            for (int i = 0; i < student_.size(); i++) {
                output.writeMessage(3, student_.get(i));
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1)
                return size;

            size = 0;
            if (id_ != 0) {
                size += com.google.protobuf.CodedOutputStream.computeInt32Size(1, id_);
            }
            if (!getCourseNameBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessage.computeStringSize(2, courseName_);
            }
            for (int i = 0; i < student_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream.computeMessageSize(3, student_.get(i));
            }
            memoizedSize = size;
            return size;
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @Override
        public com.google.protobuf.Parser<Course> getParserForType() {
            return PARSER;
        }

        public Course getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code baeldung.Course}
         */
        public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:baeldung.Course)
                CourseOrBuilder {
            private int bitField0_;
            private int id_;
            private Object courseName_ = "";
            private java.util.List<Student> student_ = java.util.Collections.emptyList();
            private com.google.protobuf.RepeatedFieldBuilder<Student, Student.Builder, StudentOrBuilder> studentBuilder_;

            // Construct using com.baeldung.protobuf.BaeldungTraining.Course.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return BaeldungTraining.internal_static_baeldung_Course_descriptor;
            }

            protected FieldAccessorTable internalGetFieldAccessorTable() {
                return BaeldungTraining.internal_static_baeldung_Course_fieldAccessorTable.ensureFieldAccessorsInitialized(Course.class, Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                    getStudentFieldBuilder();
                }
            }

            public Builder clear() {
                super.clear();
                id_ = 0;

                courseName_ = "";

                if (studentBuilder_ == null) {
                    student_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000004);
                } else {
                    studentBuilder_.clear();
                }
                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return BaeldungTraining.internal_static_baeldung_Course_descriptor;
            }

            public Course getDefaultInstanceForType() {
                return Course.getDefaultInstance();
            }

            public Course build() {
                Course result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public Course buildPartial() {
                Course result = new Course(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                result.id_ = id_;
                result.courseName_ = courseName_;
                if (studentBuilder_ == null) {
                    if (((bitField0_ & 0x00000004) == 0x00000004)) {
                        student_ = java.util.Collections.unmodifiableList(student_);
                        bitField0_ = (bitField0_ & ~0x00000004);
                    }
                    result.student_ = student_;
                } else {
                    result.student_ = studentBuilder_.build();
                }
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof Course) {
                    return mergeFrom((Course) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(Course other) {
                if (other == Course.getDefaultInstance())
                    return this;
                if (other.getId() != 0) {
                    setId(other.getId());
                }
                if (!other.getCourseName().isEmpty()) {
                    courseName_ = other.courseName_;
                    onChanged();
                }
                if (studentBuilder_ == null) {
                    if (!other.student_.isEmpty()) {
                        if (student_.isEmpty()) {
                            student_ = other.student_;
                            bitField0_ = (bitField0_ & ~0x00000004);
                        } else {
                            ensureStudentIsMutable();
                            student_.addAll(other.student_);
                        }
                        onChanged();
                    }
                } else {
                    if (!other.student_.isEmpty()) {
                        if (studentBuilder_.isEmpty()) {
                            studentBuilder_.dispose();
                            studentBuilder_ = null;
                            student_ = other.student_;
                            bitField0_ = (bitField0_ & ~0x00000004);
                            studentBuilder_ = com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ? getStudentFieldBuilder() : null;
                        } else {
                            studentBuilder_.addAllMessages(other.student_);
                        }
                    }
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
                Course parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (Course) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>optional int32 id = 1;</code>
             */
            public int getId() {
                return id_;
            }

            /**
             * <code>optional int32 id = 1;</code>
             */
            public Builder setId(int value) {

                id_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional int32 id = 1;</code>
             */
            public Builder clearId() {

                id_ = 0;
                onChanged();
                return this;
            }

            /**
             * <code>optional string course_name = 2;</code>
             */
            public String getCourseName() {
                Object ref = courseName_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    courseName_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>optional string course_name = 2;</code>
             */
            public Builder setCourseName(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                courseName_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string course_name = 2;</code>
             */
            public com.google.protobuf.ByteString getCourseNameBytes() {
                Object ref = courseName_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                    courseName_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string course_name = 2;</code>
             */
            public Builder setCourseNameBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                courseName_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string course_name = 2;</code>
             */
            public Builder clearCourseName() {

                courseName_ = getDefaultInstance().getCourseName();
                onChanged();
                return this;
            }

            private void ensureStudentIsMutable() {
                if (!((bitField0_ & 0x00000004) == 0x00000004)) {
                    student_ = new java.util.ArrayList<Student>(student_);
                    bitField0_ |= 0x00000004;
                }
            }

            /**
             * <code>repeated .baeldung.Student student = 3;</code>
             */
            public java.util.List<Student> getStudentList() {
                if (studentBuilder_ == null) {
                    return java.util.Collections.unmodifiableList(student_);
                } else {
                    return studentBuilder_.getMessageList();
                }
            }

            /**
             * <code>repeated .baeldung.Student student = 3;</code>
             */
            public int getStudentCount() {
                if (studentBuilder_ == null) {
                    return student_.size();
                } else {
                    return studentBuilder_.getCount();
                }
            }

            /**
             * <code>repeated .baeldung.Student student = 3;</code>
             */
            public Student getStudent(int index) {
                if (studentBuilder_ == null) {
                    return student_.get(index);
                } else {
                    return studentBuilder_.getMessage(index);
                }
            }

            /**
             * <code>repeated .baeldung.Student student = 3;</code>
             */
            public Builder setStudent(int index, Student value) {
                if (studentBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureStudentIsMutable();
                    student_.set(index, value);
                    onChanged();
                } else {
                    studentBuilder_.setMessage(index, value);
                }
                return this;
            }

            /**
             * <code>repeated .baeldung.Student student = 3;</code>
             */
            public Builder setStudent(int index, Student.Builder builderForValue) {
                if (studentBuilder_ == null) {
                    ensureStudentIsMutable();
                    student_.set(index, builderForValue.build());
                    onChanged();
                } else {
                    studentBuilder_.setMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .baeldung.Student student = 3;</code>
             */
            public Builder addStudent(Student value) {
                if (studentBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureStudentIsMutable();
                    student_.add(value);
                    onChanged();
                } else {
                    studentBuilder_.addMessage(value);
                }
                return this;
            }

            /**
             * <code>repeated .baeldung.Student student = 3;</code>
             */
            public Builder addStudent(int index, Student value) {
                if (studentBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureStudentIsMutable();
                    student_.add(index, value);
                    onChanged();
                } else {
                    studentBuilder_.addMessage(index, value);
                }
                return this;
            }

            /**
             * <code>repeated .baeldung.Student student = 3;</code>
             */
            public Builder addStudent(Student.Builder builderForValue) {
                if (studentBuilder_ == null) {
                    ensureStudentIsMutable();
                    student_.add(builderForValue.build());
                    onChanged();
                } else {
                    studentBuilder_.addMessage(builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .baeldung.Student student = 3;</code>
             */
            public Builder addStudent(int index, Student.Builder builderForValue) {
                if (studentBuilder_ == null) {
                    ensureStudentIsMutable();
                    student_.add(index, builderForValue.build());
                    onChanged();
                } else {
                    studentBuilder_.addMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .baeldung.Student student = 3;</code>
             */
            public Builder addAllStudent(Iterable<? extends Student> values) {
                if (studentBuilder_ == null) {
                    ensureStudentIsMutable();
                    com.google.protobuf.AbstractMessageLite.Builder.addAll(values, student_);
                    onChanged();
                } else {
                    studentBuilder_.addAllMessages(values);
                }
                return this;
            }

            /**
             * <code>repeated .baeldung.Student student = 3;</code>
             */
            public Builder clearStudent() {
                if (studentBuilder_ == null) {
                    student_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000004);
                    onChanged();
                } else {
                    studentBuilder_.clear();
                }
                return this;
            }

            /**
             * <code>repeated .baeldung.Student student = 3;</code>
             */
            public Builder removeStudent(int index) {
                if (studentBuilder_ == null) {
                    ensureStudentIsMutable();
                    student_.remove(index);
                    onChanged();
                } else {
                    studentBuilder_.remove(index);
                }
                return this;
            }

            /**
             * <code>repeated .baeldung.Student student = 3;</code>
             */
            public Student.Builder getStudentBuilder(int index) {
                return getStudentFieldBuilder().getBuilder(index);
            }

            /**
             * <code>repeated .baeldung.Student student = 3;</code>
             */
            public StudentOrBuilder getStudentOrBuilder(int index) {
                if (studentBuilder_ == null) {
                    return student_.get(index);
                } else {
                    return studentBuilder_.getMessageOrBuilder(index);
                }
            }

            /**
             * <code>repeated .baeldung.Student student = 3;</code>
             */
            public java.util.List<? extends StudentOrBuilder> getStudentOrBuilderList() {
                if (studentBuilder_ != null) {
                    return studentBuilder_.getMessageOrBuilderList();
                } else {
                    return java.util.Collections.unmodifiableList(student_);
                }
            }

            /**
             * <code>repeated .baeldung.Student student = 3;</code>
             */
            public Student.Builder addStudentBuilder() {
                return getStudentFieldBuilder().addBuilder(Student.getDefaultInstance());
            }

            /**
             * <code>repeated .baeldung.Student student = 3;</code>
             */
            public Student.Builder addStudentBuilder(int index) {
                return getStudentFieldBuilder().addBuilder(index, Student.getDefaultInstance());
            }

            /**
             * <code>repeated .baeldung.Student student = 3;</code>
             */
            public java.util.List<Student.Builder> getStudentBuilderList() {
                return getStudentFieldBuilder().getBuilderList();
            }

            private com.google.protobuf.RepeatedFieldBuilder<Student, Student.Builder, StudentOrBuilder> getStudentFieldBuilder() {
                if (studentBuilder_ == null) {
                    studentBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<Student, Student.Builder, StudentOrBuilder>(student_,
                            ((bitField0_ & 0x00000004) == 0x00000004), getParentForChildren(), isClean());
                    student_ = null;
                }
                return studentBuilder_;
            }

            public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            // @@protoc_insertion_point(builder_scope:baeldung.Course)
        }

    }

    /**
     * Protobuf type {@code baeldung.Student}
     */
    public static final class Student extends com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:baeldung.Student)
            StudentOrBuilder {
        public static final int ID_FIELD_NUMBER = 1;
        public static final int FIRST_NAME_FIELD_NUMBER = 2;
        public static final int LAST_NAME_FIELD_NUMBER = 3;
        public static final int EMAIL_FIELD_NUMBER = 4;
        public static final int PHONE_FIELD_NUMBER = 5;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:baeldung.Student)
        private static final Student DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<Student> PARSER = new com.google.protobuf.AbstractParser<Student>() {
            public Student parsePartialFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
                return new Student(input, extensionRegistry);
            }
        };

        static {
            DEFAULT_INSTANCE = new Student();
        }

        private int bitField0_;
        private int id_;
        private volatile Object firstName_;
        private volatile Object lastName_;
        private volatile Object email_;
        private java.util.List<PhoneNumber> phone_;
        private byte memoizedIsInitialized = -1;

        // Use Student.newBuilder() to construct.
        private Student(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
        }

        private Student() {
            id_ = 0;
            firstName_ = "";
            lastName_ = "";
            email_ = "";
            phone_ = java.util.Collections.emptyList();
        }

        private Student(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {

                            id_ = input.readInt32();
                            break;
                        }
                        case 18: {
                            String s = input.readStringRequireUtf8();

                            firstName_ = s;
                            break;
                        }
                        case 26: {
                            String s = input.readStringRequireUtf8();

                            lastName_ = s;
                            break;
                        }
                        case 34: {
                            String s = input.readStringRequireUtf8();

                            email_ = s;
                            break;
                        }
                        case 42: {
                            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                                phone_ = new java.util.ArrayList<PhoneNumber>();
                                mutable_bitField0_ |= 0x00000010;
                            }
                            phone_.add(input.readMessage(PhoneNumber.parser(), extensionRegistry));
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                    phone_ = java.util.Collections.unmodifiableList(phone_);
                }
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return BaeldungTraining.internal_static_baeldung_Student_descriptor;
        }

        public static Student parseFrom(com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Student parseFrom(com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Student parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Student parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Student parseFrom(java.io.InputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
        }

        public static Student parseFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Student parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input);
        }

        public static Student parseDelimitedFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static Student parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
        }

        public static Student parseFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(Student prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static Student getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<Student> parser() {
            return PARSER;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        protected FieldAccessorTable internalGetFieldAccessorTable() {
            return BaeldungTraining.internal_static_baeldung_Student_fieldAccessorTable.ensureFieldAccessorsInitialized(Student.class, Builder.class);
        }

        /**
         * <code>optional int32 id = 1;</code>
         */
        public int getId() {
            return id_;
        }

        /**
         * <code>optional string first_name = 2;</code>
         */
        public String getFirstName() {
            Object ref = firstName_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                firstName_ = s;
                return s;
            }
        }

        /**
         * <code>optional string first_name = 2;</code>
         */
        public com.google.protobuf.ByteString getFirstNameBytes() {
            Object ref = firstName_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                firstName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>optional string last_name = 3;</code>
         */
        public String getLastName() {
            Object ref = lastName_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                lastName_ = s;
                return s;
            }
        }

        /**
         * <code>optional string last_name = 3;</code>
         */
        public com.google.protobuf.ByteString getLastNameBytes() {
            Object ref = lastName_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                lastName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>optional string email = 4;</code>
         */
        public String getEmail() {
            Object ref = email_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                email_ = s;
                return s;
            }
        }

        /**
         * <code>optional string email = 4;</code>
         */
        public com.google.protobuf.ByteString getEmailBytes() {
            Object ref = email_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                email_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>repeated .baeldung.Student.PhoneNumber phone = 5;</code>
         */
        public java.util.List<PhoneNumber> getPhoneList() {
            return phone_;
        }

        /**
         * <code>repeated .baeldung.Student.PhoneNumber phone = 5;</code>
         */
        public java.util.List<? extends PhoneNumberOrBuilder> getPhoneOrBuilderList() {
            return phone_;
        }

        /**
         * <code>repeated .baeldung.Student.PhoneNumber phone = 5;</code>
         */
        public int getPhoneCount() {
            return phone_.size();
        }

        /**
         * <code>repeated .baeldung.Student.PhoneNumber phone = 5;</code>
         */
        public PhoneNumber getPhone(int index) {
            return phone_.get(index);
        }

        /**
         * <code>repeated .baeldung.Student.PhoneNumber phone = 5;</code>
         */
        public PhoneNumberOrBuilder getPhoneOrBuilder(int index) {
            return phone_.get(index);
        }

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1)
                return true;
            if (isInitialized == 0)
                return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
            if (id_ != 0) {
                output.writeInt32(1, id_);
            }
            if (!getFirstNameBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessage.writeString(output, 2, firstName_);
            }
            if (!getLastNameBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessage.writeString(output, 3, lastName_);
            }
            if (!getEmailBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessage.writeString(output, 4, email_);
            }
            for (int i = 0; i < phone_.size(); i++) {
                output.writeMessage(5, phone_.get(i));
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1)
                return size;

            size = 0;
            if (id_ != 0) {
                size += com.google.protobuf.CodedOutputStream.computeInt32Size(1, id_);
            }
            if (!getFirstNameBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessage.computeStringSize(2, firstName_);
            }
            if (!getLastNameBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessage.computeStringSize(3, lastName_);
            }
            if (!getEmailBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessage.computeStringSize(4, email_);
            }
            for (int i = 0; i < phone_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream.computeMessageSize(5, phone_.get(i));
            }
            memoizedSize = size;
            return size;
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @Override
        public com.google.protobuf.Parser<Student> getParserForType() {
            return PARSER;
        }

        public Student getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf enum {@code baeldung.Student.PhoneType}
         */
        public enum PhoneType implements com.google.protobuf.ProtocolMessageEnum {
            /**
             * <code>MOBILE = 0;</code>
             */
            MOBILE(0),
            /**
             * <code>LANDLINE = 1;</code>
             */
            LANDLINE(1), UNRECOGNIZED(-1),
            ;

            /**
             * <code>MOBILE = 0;</code>
             */
            public static final int MOBILE_VALUE = 0;
            /**
             * <code>LANDLINE = 1;</code>
             */
            public static final int LANDLINE_VALUE = 1;
            private static final com.google.protobuf.Internal.EnumLiteMap<PhoneType> internalValueMap = new com.google.protobuf.Internal.EnumLiteMap<PhoneType>() {
                public PhoneType findValueByNumber(int number) {
                    return PhoneType.forNumber(number);
                }
            };
            private static final PhoneType[] VALUES = values();
            private final int value;

            private PhoneType(int value) {
                this.value = value;
            }

            /**
             * @deprecated Use {@link #forNumber(int)} instead.
             */
            @Deprecated
            public static PhoneType valueOf(int value) {
                return forNumber(value);
            }

            public static PhoneType forNumber(int value) {
                switch (value) {
                    case 0:
                        return MOBILE;
                    case 1:
                        return LANDLINE;
                    default:
                        return null;
                }
            }

            public static com.google.protobuf.Internal.EnumLiteMap<PhoneType> internalGetValueMap() {
                return internalValueMap;
            }

            public static final com.google.protobuf.Descriptors.EnumDescriptor getDescriptor() {
                return Student.getDescriptor().getEnumTypes().get(0);
            }

            public static PhoneType valueOf(com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
                if (desc.getType() != getDescriptor()) {
                    throw new IllegalArgumentException("EnumValueDescriptor is not for this type.");
                }
                if (desc.getIndex() == -1) {
                    return UNRECOGNIZED;
                }
                return VALUES[desc.getIndex()];
            }

            public final int getNumber() {
                if (this == UNRECOGNIZED) {
                    throw new IllegalArgumentException("Can't get the number of an unknown enum value.");
                }
                return value;
            }

            public final com.google.protobuf.Descriptors.EnumValueDescriptor getValueDescriptor() {
                return getDescriptor().getValues().get(ordinal());
            }

            public final com.google.protobuf.Descriptors.EnumDescriptor getDescriptorForType() {
                return getDescriptor();
            }

            // @@protoc_insertion_point(enum_scope:baeldung.Student.PhoneType)
        }

        public interface PhoneNumberOrBuilder extends
                // @@protoc_insertion_point(interface_extends:baeldung.Student.PhoneNumber)
                com.google.protobuf.MessageOrBuilder {

            /**
             * <code>optional string number = 1;</code>
             */
            String getNumber();

            /**
             * <code>optional string number = 1;</code>
             */
            com.google.protobuf.ByteString getNumberBytes();

            /**
             * <code>optional .baeldung.Student.PhoneType type = 2;</code>
             */
            int getTypeValue();

            /**
             * <code>optional .baeldung.Student.PhoneType type = 2;</code>
             */
            PhoneType getType();
        }

        /**
         * Protobuf type {@code baeldung.Student.PhoneNumber}
         */
        public static final class PhoneNumber extends com.google.protobuf.GeneratedMessage implements
                // @@protoc_insertion_point(message_implements:baeldung.Student.PhoneNumber)
                PhoneNumberOrBuilder {
            public static final int NUMBER_FIELD_NUMBER = 1;
            public static final int TYPE_FIELD_NUMBER = 2;
            private static final long serialVersionUID = 0L;
            // @@protoc_insertion_point(class_scope:baeldung.Student.PhoneNumber)
            private static final PhoneNumber DEFAULT_INSTANCE;
            private static final com.google.protobuf.Parser<PhoneNumber> PARSER = new com.google.protobuf.AbstractParser<PhoneNumber>() {
                public PhoneNumber parsePartialFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
                    return new PhoneNumber(input, extensionRegistry);
                }
            };

            static {
                DEFAULT_INSTANCE = new PhoneNumber();
            }

            private volatile Object number_;
            private int type_;
            private byte memoizedIsInitialized = -1;

            // Use PhoneNumber.newBuilder() to construct.
            private PhoneNumber(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
                super(builder);
            }

            private PhoneNumber() {
                number_ = "";
                type_ = 0;
            }

            private PhoneNumber(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
                this();
                int mutable_bitField0_ = 0;
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            default: {
                                if (!input.skipField(tag)) {
                                    done = true;
                                }
                                break;
                            }
                            case 10: {
                                String s = input.readStringRequireUtf8();

                                number_ = s;
                                break;
                            }
                            case 16: {
                                int rawValue = input.readEnum();

                                type_ = rawValue;
                                break;
                            }
                        }
                    }
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(this);
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
                } finally {
                    makeExtensionsImmutable();
                }
            }

            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return BaeldungTraining.internal_static_baeldung_Student_PhoneNumber_descriptor;
            }

            public static PhoneNumber parseFrom(com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data);
            }

            public static PhoneNumber parseFrom(com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data, extensionRegistry);
            }

            public static PhoneNumber parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data);
            }

            public static PhoneNumber parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data, extensionRegistry);
            }

            public static PhoneNumber parseFrom(java.io.InputStream input) throws java.io.IOException {
                return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
            }

            public static PhoneNumber parseFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
                return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);
            }

            public static PhoneNumber parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
                return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input);
            }

            public static PhoneNumber parseDelimitedFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
                return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
            }

            public static PhoneNumber parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
                return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
            }

            public static PhoneNumber parseFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
                return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);
            }

            public static Builder newBuilder() {
                return DEFAULT_INSTANCE.toBuilder();
            }

            public static Builder newBuilder(PhoneNumber prototype) {
                return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
            }

            public static PhoneNumber getDefaultInstance() {
                return DEFAULT_INSTANCE;
            }

            public static com.google.protobuf.Parser<PhoneNumber> parser() {
                return PARSER;
            }

            @Override
            public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
                return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
            }

            protected FieldAccessorTable internalGetFieldAccessorTable() {
                return BaeldungTraining.internal_static_baeldung_Student_PhoneNumber_fieldAccessorTable.ensureFieldAccessorsInitialized(PhoneNumber.class,
                        Builder.class);
            }

            /**
             * <code>optional string number = 1;</code>
             */
            public String getNumber() {
                Object ref = number_;
                if (ref instanceof String) {
                    return (String) ref;
                } else {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    number_ = s;
                    return s;
                }
            }

            /**
             * <code>optional string number = 1;</code>
             */
            public com.google.protobuf.ByteString getNumberBytes() {
                Object ref = number_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                    number_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional .baeldung.Student.PhoneType type = 2;</code>
             */
            public int getTypeValue() {
                return type_;
            }

            /**
             * <code>optional .baeldung.Student.PhoneType type = 2;</code>
             */
            public PhoneType getType() {
                PhoneType result = PhoneType.forNumber(type_);
                return result == null ? PhoneType.UNRECOGNIZED : result;
            }

            public final boolean isInitialized() {
                byte isInitialized = memoizedIsInitialized;
                if (isInitialized == 1)
                    return true;
                if (isInitialized == 0)
                    return false;

                memoizedIsInitialized = 1;
                return true;
            }

            public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
                if (!getNumberBytes().isEmpty()) {
                    com.google.protobuf.GeneratedMessage.writeString(output, 1, number_);
                }
                if (type_ != PhoneType.MOBILE.getNumber()) {
                    output.writeEnum(2, type_);
                }
            }

            public int getSerializedSize() {
                int size = memoizedSize;
                if (size != -1)
                    return size;

                size = 0;
                if (!getNumberBytes().isEmpty()) {
                    size += com.google.protobuf.GeneratedMessage.computeStringSize(1, number_);
                }
                if (type_ != PhoneType.MOBILE.getNumber()) {
                    size += com.google.protobuf.CodedOutputStream.computeEnumSize(2, type_);
                }
                memoizedSize = size;
                return size;
            }

            public Builder newBuilderForType() {
                return newBuilder();
            }

            public Builder toBuilder() {
                return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
            }

            @Override
            protected Builder newBuilderForType(BuilderParent parent) {
                Builder builder = new Builder(parent);
                return builder;
            }

            @Override
            public com.google.protobuf.Parser<PhoneNumber> getParserForType() {
                return PARSER;
            }

            public PhoneNumber getDefaultInstanceForType() {
                return DEFAULT_INSTANCE;
            }

            /**
             * Protobuf type {@code baeldung.Student.PhoneNumber}
             */
            public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                    // @@protoc_insertion_point(builder_implements:baeldung.Student.PhoneNumber)
                    PhoneNumberOrBuilder {
                private Object number_ = "";
                private int type_ = 0;

                // Construct using com.baeldung.protobuf.BaeldungTraining.Student.PhoneNumber.newBuilder()
                private Builder() {
                    maybeForceBuilderInitialization();
                }

                private Builder(BuilderParent parent) {
                    super(parent);
                    maybeForceBuilderInitialization();
                }

                public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                    return BaeldungTraining.internal_static_baeldung_Student_PhoneNumber_descriptor;
                }

                protected FieldAccessorTable internalGetFieldAccessorTable() {
                    return BaeldungTraining.internal_static_baeldung_Student_PhoneNumber_fieldAccessorTable.ensureFieldAccessorsInitialized(PhoneNumber.class,
                            Builder.class);
                }

                private void maybeForceBuilderInitialization() {
                    if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                    }
                }

                public Builder clear() {
                    super.clear();
                    number_ = "";

                    type_ = 0;

                    return this;
                }

                public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                    return BaeldungTraining.internal_static_baeldung_Student_PhoneNumber_descriptor;
                }

                public PhoneNumber getDefaultInstanceForType() {
                    return PhoneNumber.getDefaultInstance();
                }

                public PhoneNumber build() {
                    PhoneNumber result = buildPartial();
                    if (!result.isInitialized()) {
                        throw newUninitializedMessageException(result);
                    }
                    return result;
                }

                public PhoneNumber buildPartial() {
                    PhoneNumber result = new PhoneNumber(this);
                    result.number_ = number_;
                    result.type_ = type_;
                    onBuilt();
                    return result;
                }

                public Builder mergeFrom(com.google.protobuf.Message other) {
                    if (other instanceof PhoneNumber) {
                        return mergeFrom((PhoneNumber) other);
                    } else {
                        super.mergeFrom(other);
                        return this;
                    }
                }

                public Builder mergeFrom(PhoneNumber other) {
                    if (other == PhoneNumber.getDefaultInstance())
                        return this;
                    if (!other.getNumber().isEmpty()) {
                        number_ = other.number_;
                        onChanged();
                    }
                    if (other.type_ != 0) {
                        setTypeValue(other.getTypeValue());
                    }
                    onChanged();
                    return this;
                }

                public final boolean isInitialized() {
                    return true;
                }

                public Builder mergeFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
                    PhoneNumber parsedMessage = null;
                    try {
                        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                        parsedMessage = (PhoneNumber) e.getUnfinishedMessage();
                        throw e.unwrapIOException();
                    } finally {
                        if (parsedMessage != null) {
                            mergeFrom(parsedMessage);
                        }
                    }
                    return this;
                }

                /**
                 * <code>optional string number = 1;</code>
                 */
                public String getNumber() {
                    Object ref = number_;
                    if (!(ref instanceof String)) {
                        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                        String s = bs.toStringUtf8();
                        number_ = s;
                        return s;
                    } else {
                        return (String) ref;
                    }
                }

                /**
                 * <code>optional string number = 1;</code>
                 */
                public Builder setNumber(String value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }

                    number_ = value;
                    onChanged();
                    return this;
                }

                /**
                 * <code>optional string number = 1;</code>
                 */
                public com.google.protobuf.ByteString getNumberBytes() {
                    Object ref = number_;
                    if (ref instanceof String) {
                        com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                        number_ = b;
                        return b;
                    } else {
                        return (com.google.protobuf.ByteString) ref;
                    }
                }

                /**
                 * <code>optional string number = 1;</code>
                 */
                public Builder setNumberBytes(com.google.protobuf.ByteString value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    checkByteStringIsUtf8(value);

                    number_ = value;
                    onChanged();
                    return this;
                }

                /**
                 * <code>optional string number = 1;</code>
                 */
                public Builder clearNumber() {

                    number_ = getDefaultInstance().getNumber();
                    onChanged();
                    return this;
                }

                /**
                 * <code>optional .baeldung.Student.PhoneType type = 2;</code>
                 */
                public int getTypeValue() {
                    return type_;
                }

                /**
                 * <code>optional .baeldung.Student.PhoneType type = 2;</code>
                 */
                public Builder setTypeValue(int value) {
                    type_ = value;
                    onChanged();
                    return this;
                }

                /**
                 * <code>optional .baeldung.Student.PhoneType type = 2;</code>
                 */
                public PhoneType getType() {
                    PhoneType result = PhoneType.forNumber(type_);
                    return result == null ? PhoneType.UNRECOGNIZED : result;
                }

                /**
                 * <code>optional .baeldung.Student.PhoneType type = 2;</code>
                 */
                public Builder setType(PhoneType value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }

                    type_ = value.getNumber();
                    onChanged();
                    return this;
                }

                /**
                 * <code>optional .baeldung.Student.PhoneType type = 2;</code>
                 */
                public Builder clearType() {

                    type_ = 0;
                    onChanged();
                    return this;
                }

                public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                    return this;
                }

                public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                    return this;
                }

                // @@protoc_insertion_point(builder_scope:baeldung.Student.PhoneNumber)
            }

        }

        /**
         * Protobuf type {@code baeldung.Student}
         */
        public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:baeldung.Student)
                StudentOrBuilder {
            private int bitField0_;
            private int id_;
            private Object firstName_ = "";
            private Object lastName_ = "";
            private Object email_ = "";
            private java.util.List<PhoneNumber> phone_ = java.util.Collections.emptyList();
            private com.google.protobuf.RepeatedFieldBuilder<PhoneNumber, PhoneNumber.Builder, PhoneNumberOrBuilder> phoneBuilder_;

            // Construct using com.baeldung.protobuf.BaeldungTraining.Student.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return BaeldungTraining.internal_static_baeldung_Student_descriptor;
            }

            protected FieldAccessorTable internalGetFieldAccessorTable() {
                return BaeldungTraining.internal_static_baeldung_Student_fieldAccessorTable.ensureFieldAccessorsInitialized(Student.class,
                        Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                    getPhoneFieldBuilder();
                }
            }

            public Builder clear() {
                super.clear();
                id_ = 0;

                firstName_ = "";

                lastName_ = "";

                email_ = "";

                if (phoneBuilder_ == null) {
                    phone_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000010);
                } else {
                    phoneBuilder_.clear();
                }
                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return BaeldungTraining.internal_static_baeldung_Student_descriptor;
            }

            public Student getDefaultInstanceForType() {
                return Student.getDefaultInstance();
            }

            public Student build() {
                Student result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public Student buildPartial() {
                Student result = new Student(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                result.id_ = id_;
                result.firstName_ = firstName_;
                result.lastName_ = lastName_;
                result.email_ = email_;
                if (phoneBuilder_ == null) {
                    if (((bitField0_ & 0x00000010) == 0x00000010)) {
                        phone_ = java.util.Collections.unmodifiableList(phone_);
                        bitField0_ = (bitField0_ & ~0x00000010);
                    }
                    result.phone_ = phone_;
                } else {
                    result.phone_ = phoneBuilder_.build();
                }
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof Student) {
                    return mergeFrom((Student) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(Student other) {
                if (other == Student.getDefaultInstance())
                    return this;
                if (other.getId() != 0) {
                    setId(other.getId());
                }
                if (!other.getFirstName().isEmpty()) {
                    firstName_ = other.firstName_;
                    onChanged();
                }
                if (!other.getLastName().isEmpty()) {
                    lastName_ = other.lastName_;
                    onChanged();
                }
                if (!other.getEmail().isEmpty()) {
                    email_ = other.email_;
                    onChanged();
                }
                if (phoneBuilder_ == null) {
                    if (!other.phone_.isEmpty()) {
                        if (phone_.isEmpty()) {
                            phone_ = other.phone_;
                            bitField0_ = (bitField0_ & ~0x00000010);
                        } else {
                            ensurePhoneIsMutable();
                            phone_.addAll(other.phone_);
                        }
                        onChanged();
                    }
                } else {
                    if (!other.phone_.isEmpty()) {
                        if (phoneBuilder_.isEmpty()) {
                            phoneBuilder_.dispose();
                            phoneBuilder_ = null;
                            phone_ = other.phone_;
                            bitField0_ = (bitField0_ & ~0x00000010);
                            phoneBuilder_ = com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ? getPhoneFieldBuilder() : null;
                        } else {
                            phoneBuilder_.addAllMessages(other.phone_);
                        }
                    }
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
                Student parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (Student) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>optional int32 id = 1;</code>
             */
            public int getId() {
                return id_;
            }

            /**
             * <code>optional int32 id = 1;</code>
             */
            public Builder setId(int value) {

                id_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional int32 id = 1;</code>
             */
            public Builder clearId() {

                id_ = 0;
                onChanged();
                return this;
            }

            /**
             * <code>optional string first_name = 2;</code>
             */
            public String getFirstName() {
                Object ref = firstName_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    firstName_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>optional string first_name = 2;</code>
             */
            public Builder setFirstName(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                firstName_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string first_name = 2;</code>
             */
            public com.google.protobuf.ByteString getFirstNameBytes() {
                Object ref = firstName_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                    firstName_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string first_name = 2;</code>
             */
            public Builder setFirstNameBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                firstName_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string first_name = 2;</code>
             */
            public Builder clearFirstName() {

                firstName_ = getDefaultInstance().getFirstName();
                onChanged();
                return this;
            }

            /**
             * <code>optional string last_name = 3;</code>
             */
            public String getLastName() {
                Object ref = lastName_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    lastName_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>optional string last_name = 3;</code>
             */
            public Builder setLastName(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                lastName_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string last_name = 3;</code>
             */
            public com.google.protobuf.ByteString getLastNameBytes() {
                Object ref = lastName_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                    lastName_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string last_name = 3;</code>
             */
            public Builder setLastNameBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                lastName_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string last_name = 3;</code>
             */
            public Builder clearLastName() {

                lastName_ = getDefaultInstance().getLastName();
                onChanged();
                return this;
            }

            /**
             * <code>optional string email = 4;</code>
             */
            public String getEmail() {
                Object ref = email_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    email_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>optional string email = 4;</code>
             */
            public Builder setEmail(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                email_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string email = 4;</code>
             */
            public com.google.protobuf.ByteString getEmailBytes() {
                Object ref = email_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                    email_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string email = 4;</code>
             */
            public Builder setEmailBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                email_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string email = 4;</code>
             */
            public Builder clearEmail() {

                email_ = getDefaultInstance().getEmail();
                onChanged();
                return this;
            }

            private void ensurePhoneIsMutable() {
                if (!((bitField0_ & 0x00000010) == 0x00000010)) {
                    phone_ = new java.util.ArrayList<PhoneNumber>(phone_);
                    bitField0_ |= 0x00000010;
                }
            }

            /**
             * <code>repeated .baeldung.Student.PhoneNumber phone = 5;</code>
             */
            public java.util.List<PhoneNumber> getPhoneList() {
                if (phoneBuilder_ == null) {
                    return java.util.Collections.unmodifiableList(phone_);
                } else {
                    return phoneBuilder_.getMessageList();
                }
            }

            /**
             * <code>repeated .baeldung.Student.PhoneNumber phone = 5;</code>
             */
            public int getPhoneCount() {
                if (phoneBuilder_ == null) {
                    return phone_.size();
                } else {
                    return phoneBuilder_.getCount();
                }
            }

            /**
             * <code>repeated .baeldung.Student.PhoneNumber phone = 5;</code>
             */
            public PhoneNumber getPhone(int index) {
                if (phoneBuilder_ == null) {
                    return phone_.get(index);
                } else {
                    return phoneBuilder_.getMessage(index);
                }
            }

            /**
             * <code>repeated .baeldung.Student.PhoneNumber phone = 5;</code>
             */
            public Builder setPhone(int index, PhoneNumber value) {
                if (phoneBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensurePhoneIsMutable();
                    phone_.set(index, value);
                    onChanged();
                } else {
                    phoneBuilder_.setMessage(index, value);
                }
                return this;
            }

            /**
             * <code>repeated .baeldung.Student.PhoneNumber phone = 5;</code>
             */
            public Builder setPhone(int index, PhoneNumber.Builder builderForValue) {
                if (phoneBuilder_ == null) {
                    ensurePhoneIsMutable();
                    phone_.set(index, builderForValue.build());
                    onChanged();
                } else {
                    phoneBuilder_.setMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .baeldung.Student.PhoneNumber phone = 5;</code>
             */
            public Builder addPhone(PhoneNumber value) {
                if (phoneBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensurePhoneIsMutable();
                    phone_.add(value);
                    onChanged();
                } else {
                    phoneBuilder_.addMessage(value);
                }
                return this;
            }

            /**
             * <code>repeated .baeldung.Student.PhoneNumber phone = 5;</code>
             */
            public Builder addPhone(int index, PhoneNumber value) {
                if (phoneBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensurePhoneIsMutable();
                    phone_.add(index, value);
                    onChanged();
                } else {
                    phoneBuilder_.addMessage(index, value);
                }
                return this;
            }

            /**
             * <code>repeated .baeldung.Student.PhoneNumber phone = 5;</code>
             */
            public Builder addPhone(PhoneNumber.Builder builderForValue) {
                if (phoneBuilder_ == null) {
                    ensurePhoneIsMutable();
                    phone_.add(builderForValue.build());
                    onChanged();
                } else {
                    phoneBuilder_.addMessage(builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .baeldung.Student.PhoneNumber phone = 5;</code>
             */
            public Builder addPhone(int index, PhoneNumber.Builder builderForValue) {
                if (phoneBuilder_ == null) {
                    ensurePhoneIsMutable();
                    phone_.add(index, builderForValue.build());
                    onChanged();
                } else {
                    phoneBuilder_.addMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .baeldung.Student.PhoneNumber phone = 5;</code>
             */
            public Builder addAllPhone(Iterable<? extends PhoneNumber> values) {
                if (phoneBuilder_ == null) {
                    ensurePhoneIsMutable();
                    com.google.protobuf.AbstractMessageLite.Builder.addAll(values, phone_);
                    onChanged();
                } else {
                    phoneBuilder_.addAllMessages(values);
                }
                return this;
            }

            /**
             * <code>repeated .baeldung.Student.PhoneNumber phone = 5;</code>
             */
            public Builder clearPhone() {
                if (phoneBuilder_ == null) {
                    phone_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000010);
                    onChanged();
                } else {
                    phoneBuilder_.clear();
                }
                return this;
            }

            /**
             * <code>repeated .baeldung.Student.PhoneNumber phone = 5;</code>
             */
            public Builder removePhone(int index) {
                if (phoneBuilder_ == null) {
                    ensurePhoneIsMutable();
                    phone_.remove(index);
                    onChanged();
                } else {
                    phoneBuilder_.remove(index);
                }
                return this;
            }

            /**
             * <code>repeated .baeldung.Student.PhoneNumber phone = 5;</code>
             */
            public PhoneNumber.Builder getPhoneBuilder(int index) {
                return getPhoneFieldBuilder().getBuilder(index);
            }

            /**
             * <code>repeated .baeldung.Student.PhoneNumber phone = 5;</code>
             */
            public PhoneNumberOrBuilder getPhoneOrBuilder(int index) {
                if (phoneBuilder_ == null) {
                    return phone_.get(index);
                } else {
                    return phoneBuilder_.getMessageOrBuilder(index);
                }
            }

            /**
             * <code>repeated .baeldung.Student.PhoneNumber phone = 5;</code>
             */
            public java.util.List<? extends PhoneNumberOrBuilder> getPhoneOrBuilderList() {
                if (phoneBuilder_ != null) {
                    return phoneBuilder_.getMessageOrBuilderList();
                } else {
                    return java.util.Collections.unmodifiableList(phone_);
                }
            }

            /**
             * <code>repeated .baeldung.Student.PhoneNumber phone = 5;</code>
             */
            public PhoneNumber.Builder addPhoneBuilder() {
                return getPhoneFieldBuilder().addBuilder(PhoneNumber.getDefaultInstance());
            }

            /**
             * <code>repeated .baeldung.Student.PhoneNumber phone = 5;</code>
             */
            public PhoneNumber.Builder addPhoneBuilder(int index) {
                return getPhoneFieldBuilder().addBuilder(index, PhoneNumber.getDefaultInstance());
            }

            /**
             * <code>repeated .baeldung.Student.PhoneNumber phone = 5;</code>
             */
            public java.util.List<PhoneNumber.Builder> getPhoneBuilderList() {
                return getPhoneFieldBuilder().getBuilderList();
            }

            private com.google.protobuf.RepeatedFieldBuilder<PhoneNumber, PhoneNumber.Builder, PhoneNumberOrBuilder> getPhoneFieldBuilder() {
                if (phoneBuilder_ == null) {
                    phoneBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<PhoneNumber, PhoneNumber.Builder, PhoneNumberOrBuilder>(
                            phone_, ((bitField0_ & 0x00000010) == 0x00000010), getParentForChildren(), isClean());
                    phone_ = null;
                }
                return phoneBuilder_;
            }

            public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            // @@protoc_insertion_point(builder_scope:baeldung.Student)
        }

    }

    // @@protoc_insertion_point(outer_class_scope)
}
